
import { useEffect, useState } from 'react'

import type { NextPage } from 'next'
import Head from 'next/head'
import dynamic from "next/dynamic";

import { format } from 'fecha'

import styles from '../styles/Home.module.scss'

const ThemeToogle = dynamic(() => import('../components/theme'), { ssr: false })
const AccountButton = dynamic(() => import('../components/AccountButton'), { ssr: false })

const Home: NextPage = () => {
  const [time, setTime] = useState('--:--:--')

  useEffect(() => {
    const timer = setInterval(() => {
      setTime(format(new Date(), 'HH:mm:ss'))
    }, 1000)

    return () => {
      clearInterval(timer)
    }
  }, [])

  const renderLeft = () => {
    return (
      <div className={styles.left}>
        <div className='hd'>
          <AccountButton />
          <div className={styles['mod-user']}>
            <div className={styles.user}>
              <div className="name">Name</div>
              <div className="number">#1080</div>
            </div>
            <div className="bd">
            </div>
          </div>

          <div className={styles['mod-search']}></div>
        </div>

        <div className='bd'>
          <div className={styles.section} style={{marginBottom: '40px'}}>
            <div className='hd'>Group</div>
            <div className='bd'>
              <ul className='list'>
                <li># Stream_chat</li>
                <li># Stream_chat</li>
                <li># Stream_chat</li>
              </ul>
            </div>
          </div>

          <div className={styles.section}>
            <div className='hd'>Contact</div>
            <div className='bd'>
              <ul className='list'>
                <li>Mary Cooper</li>
                <li>Mary Cooper</li>
                <li>Mary Cooper</li>
                <li>Mary Cooper</li>
                <li>Mary Cooper</li>
                <li>Mary Cooper</li>
              </ul>
            </div>
          </div>
        </div>

        <div className='ft'>
          <ThemeToogle />
        </div>
      </div>
    )
  }

  const renderCenter = () => {
    return (
      <div className={styles.center}>center</div>
    )
  }
  const renderRight = () => {
    return (
      <div className={styles.right}>
        <div className={styles['mod-clock']}>
          {time}
        </div>

        <div className={styles['mod-network']}>
          <div className="hd">
            <div>PING</div>
            <div className='value'>24ms</div>
          </div>
          <div className="bd">
            <div>NETWORK STATUS</div>
            <div className='label'>STATE IPv4</div>
            <div>ONLINE</div>
          </div>
        </div>

        <div className={styles['mod-member']}>
          <div className={styles.section}>
            <div className='hd'>Moderator</div>
            <div className='bd'>
              <ul className='list'>
                <li>Mary Cooper</li>
              </ul>
            </div>
          </div>
          <div className={styles.divider}></div>
          <div className={styles.section}>
            <div className='hd'>Moderator</div>
            <div className='bd'>
              <ul className='list'>
                <li>Mary Cooper</li>
                <li>Mary Cooper</li>
                <li>Mary Cooper</li>
                <li>Mary Cooper</li>
                <li>Mary Cooper</li>
                <li>Mary Cooper</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        {renderLeft()}
        {renderCenter()}
        {renderRight()}
      </div>
        
    </div>
  )
}

export default Home
